name: Bug Report
description: Test
body:
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari  
